### ISSUE TITLE
报错了0.0

### ISSUE THREAD

**Issue by 2641062110** [zedxpp/BBS#3]
ld: library not found for -lmysqlclient for architecture x86_64  这个错，，而且我数据库运行出错呢。。

**Comment by zedxpp** [comment]
你的本地mysql服务能启动起来吗?

**Comment by zedxpp** [comment]
看你的报错，是mysql没有装好。

**Comment by 2641062110** [comment]
是启动的
运行 bbs.sql 显示报错

**Comment by zedxpp** [comment]
你的mysql是多少版本号

**Comment by 2641062110** [comment]
5.7.20

**Comment by 2641062110** [comment]
Ver 14.14 Distrib 5.7.20,

**Comment by 2641062110** [comment]
Error at query 3: No database selected  运行 bbs.sql 报Error at query 3: No database selected  这个错误

**Comment by zedxpp** [comment]
readme步骤 "新建一个bbs的数据库, 参数请务必和我图上的一致. 然后运行bbs.sql文件"      
新建我说的名叫"bbs"的数据库 并且里面的参数和我图片设置一样的没?

**Comment by 2641062110** [comment]
抱歉！
是我自己搞错了0.0

**Comment by zedxpp** [comment]
我写进去, 肯定是有道理的哦,这个坑当初也坑了我很久  -. -

**Comment by 2641062110** [comment]
0.0   很机智的操作
